// Mathwaa June Marketing Revenue Report Data
// Period: June 1–28, 2026

export interface Booking {
  id: number;
  name: string;
  name_ar: string;
  branch: string;
  location: string;
  location_ar: string;
  monthlyRent: number;
  channel: string;
  channel_ar: string;
  attribution: 'Performance/Direct' | 'Performance/Indirect' | 'Other' | 'Performance';
  attribution_ar: string;
  status: 'Approved' | 'Cancelled' | 'Renewal';
  status_ar: string;
  checkIn: string;
  checkIn_ar: string;
  juneCash: number;
  ltv: number;
}

export const BOOKINGS: Booking[] = [
  {
    id: 1,
    name: "Amal Alenazi",
    name_ar: "أمل العنزي",
    branch: "M38",
    location: "Al Sulaimaniyah",
    location_ar: "السليمانية",
    monthlyRent: 5444,
    channel: "TikTok",
    channel_ar: "تيك توك",
    attribution: "Performance/Direct",
    attribution_ar: "أداء / مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "19/6 (June)",
    checkIn_ar: "١٩/٦ (يونيو)",
    juneCash: 1361.0,
    ltv: 1701.25
  },
  {
    id: 2,
    name: "Day Aljameel",
    name_ar: "ضي الجميل",
    branch: "M23",
    location: "Al Yarmouk",
    location_ar: "اليرموك",
    monthlyRent: 4500,
    channel: "Social media",
    channel_ar: "وسائل التواصل الاجتماعي",
    attribution: "Performance/Direct",
    attribution_ar: "أداء / مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "25/6 (June)",
    checkIn_ar: "٢٥/٦ (يونيو)",
    juneCash: 1350.0,
    ltv: 4050.0
  },
  {
    id: 3,
    name: "Omaima Abdeen",
    name_ar: "أميمة عابدين",
    branch: "M20",
    location: "Al Zahraa",
    location_ar: "الزهراء",
    monthlyRent: 2500,
    channel: "Facebook ad",
    channel_ar: "إعلان فيسبوك",
    attribution: "Performance/Indirect",
    attribution_ar: "أداء / غير مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "12/6 (June)",
    checkIn_ar: "١٢/٦ (يونيو)",
    juneCash: 500.0,
    ltv: 1000.0
  },
  {
    id: 4,
    name: "Fai Alayafi",
    name_ar: "فيء العيافي",
    branch: "M32",
    location: "Al Qayrawan",
    location_ar: "القيروان",
    monthlyRent: 4500,
    channel: "TikTok",
    channel_ar: "تيك توك",
    attribution: "Performance/Direct",
    attribution_ar: "أداء / مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "9/6 (June)",
    checkIn_ar: "٩/٦ (يونيو)",
    juneCash: 1125.0,
    ltv: 6750.0
  },
  {
    id: 5,
    name: "Heba Hosawi",
    name_ar: "هبة هوساوي",
    branch: "M20",
    location: "Al Zahraa",
    location_ar: "الزهراء",
    monthlyRent: 2400,
    channel: "Instagram",
    channel_ar: "إنستغرام",
    attribution: "Performance/Indirect",
    attribution_ar: "أداء / غير مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "16/6 (June)",
    checkIn_ar: "١٦/٦ (يونيو)",
    juneCash: 480.0,
    ltv: 480.0
  },
  {
    id: 6,
    name: "Shuaa Almoghira",
    name_ar: "شعاع المغيرة",
    branch: "M38",
    location: "Al Sulaimaniyah",
    location_ar: "السليمانية",
    monthlyRent: 4790,
    channel: "Social media",
    channel_ar: "وسائل التواصل الاجتماعي",
    attribution: "Performance/Direct",
    attribution_ar: "أداء / مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "12/6 (June)",
    checkIn_ar: "١٢/٦ (يونيو)",
    juneCash: 1197.5,
    ltv: 1197.5
  },
  {
    id: 7,
    name: "Athari Alqalhati",
    name_ar: "أثاري القلحاطي",
    branch: "M37",
    location: "Al Arid",
    location_ar: "العارض",
    monthlyRent: 2600,
    channel: "Social/TikTok",
    channel_ar: "تواصل/تيك توك",
    attribution: "Performance/Direct",
    attribution_ar: "أداء / مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "19/6 (June)",
    checkIn_ar: "١٩/٦ (يونيو)",
    juneCash: 780.0,
    ltv: 780.0
  },
  {
    id: 8,
    name: "Zahraa Albasri",
    name_ar: "زهراء البصري",
    branch: "M7",
    location: "Al Arid",
    location_ar: "العارض",
    monthlyRent: 2900,
    channel: "Instagram",
    channel_ar: "إنستغرام",
    attribution: "Performance/Indirect",
    attribution_ar: "أداء / غير مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "12/6 (June)",
    checkIn_ar: "١٢/٦ (يونيو)",
    juneCash: 580.0,
    ltv: 1160.0
  },
  {
    id: 9,
    name: "Faisal Alhussaini",
    name_ar: "فيصل الحسيني",
    branch: "M13",
    location: "Al Aqiq",
    location_ar: "العقيق",
    monthlyRent: 4800,
    channel: "TikTok",
    channel_ar: "تيك توك",
    attribution: "Performance/Indirect",
    attribution_ar: "أداء / غير مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "19/6 (June)",
    checkIn_ar: "١٩/٦ (يونيو)",
    juneCash: 960.0,
    ltv: 960.0
  },
  {
    id: 10,
    name: "Shahad Alotaibi",
    name_ar: "شهد العتيبي",
    branch: "M31",
    location: "Al Salam",
    location_ar: "السلام",
    monthlyRent: 3300,
    channel: "Friend via TikTok",
    channel_ar: "صديق عبر تيك توك",
    attribution: "Performance/Direct",
    attribution_ar: "أداء / مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "1/7 (July)",
    checkIn_ar: "١/٧ (يوليو)",
    juneCash: 0.0,
    ltv: 11880.0
  },
  {
    id: 11,
    name: "Fatma Alwasmi",
    name_ar: "فاطمة الوسمي",
    branch: "M6",
    location: "Al Arid",
    location_ar: "العارض",
    monthlyRent: 2900,
    channel: "TikTok",
    channel_ar: "تيك توك",
    attribution: "Performance/Direct",
    attribution_ar: "أداء / مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "19/6 (June)",
    checkIn_ar: "١٩/٦ (يونيو)",
    juneCash: 580.0,
    ltv: 6960.0
  },
  {
    id: 12,
    name: "Dana Alshatab",
    name_ar: "دانة الشطب",
    branch: "M38",
    location: "Al Sulaimaniyah",
    location_ar: "السليمانية",
    monthlyRent: 4345,
    channel: "TikTok",
    channel_ar: "تيك توك",
    attribution: "Performance/Direct",
    attribution_ar: "أداء / مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "27/6 (June)",
    checkIn_ar: "٢٧/٦ (يونيو)",
    juneCash: 1086.25,
    ltv: 1086.25
  },
  {
    id: 13,
    name: "Shahad Alshehri",
    name_ar: "شهد الشهري",
    branch: "M51",
    location: "Al Narjis",
    location_ar: "النرجس",
    monthlyRent: 2800,
    channel: "TikTok",
    channel_ar: "تيك توك",
    attribution: "Performance/Indirect",
    attribution_ar: "أداء / غير مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "21/6 (June)",
    checkIn_ar: "٢١/٦ (يونيو)",
    juneCash: 280.0,
    ltv: 3360.0
  },
  {
    id: 14,
    name: "Sulaf Albeshi",
    name_ar: "سلاف البيشي",
    branch: "M25",
    location: "Al Yarmouk",
    location_ar: "اليرموك",
    monthlyRent: 2330,
    channel: "Instagram + friend",
    channel_ar: "إنستغرام + صديق",
    attribution: "Performance/Direct",
    attribution_ar: "أداء / مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "24/6 (June)",
    checkIn_ar: "٢٤/٦ (يونيو)",
    juneCash: 699.0,
    ltv: 699.0
  },
  {
    id: 15,
    name: "Fatma Aldosari",
    name_ar: "فاطمة الدوسري",
    branch: "M39",
    location: "Al Nakhil",
    location_ar: "النخيل",
    monthlyRent: 3300,
    channel: "Instagram",
    channel_ar: "إنستغرام",
    attribution: "Performance/Direct",
    attribution_ar: "أداء / مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "30/6 (June)",
    checkIn_ar: "٣٠/٦ (يونيو)",
    juneCash: 990.0,
    ltv: 5940.0
  },
  {
    id: 16,
    name: "Majd Alotaibi",
    name_ar: "مجد العتيبي",
    branch: "M20",
    location: "Al Zahraa",
    location_ar: "الزهراء",
    monthlyRent: 2700,
    channel: "TikTok",
    channel_ar: "تيك توك",
    attribution: "Performance/Indirect",
    attribution_ar: "أداء / غير مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "26/6 (June)",
    checkIn_ar: "٢٦/٦ (يونيو)",
    juneCash: 540.0,
    ltv: 1080.0
  },
  {
    id: 17,
    name: "Hoor Alturki",
    name_ar: "حور التركي",
    branch: "M38",
    location: "Al Sulaimaniyah",
    location_ar: "السليمانية",
    monthlyRent: 4420,
    channel: "TikTok",
    channel_ar: "تيك توك",
    attribution: "Performance/Direct",
    attribution_ar: "أداء / مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "27/6 (June)",
    checkIn_ar: "٢٧/٦ (يونيو)",
    juneCash: 1105.0,
    ltv: 2210.0
  },
  {
    id: 18,
    name: "Sarah Almutairi",
    name_ar: "سارة المطيري",
    branch: "M42",
    location: "Al Arid",
    location_ar: "العارض",
    monthlyRent: 1700,
    channel: "TikTok",
    channel_ar: "تيك توك",
    attribution: "Performance/Direct",
    attribution_ar: "أداء / مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "27/6 (June)",
    checkIn_ar: "٢٧/٦ (يونيو)",
    juneCash: 510.0,
    ltv: 6120.0
  },
  {
    id: 19,
    name: "Munira Alturki",
    name_ar: "منيرة التركي",
    branch: "M38",
    location: "Al Sulaimaniyah",
    location_ar: "السليمانية",
    monthlyRent: 4410,
    channel: "TikTok",
    channel_ar: "تيك توك",
    attribution: "Performance/Direct",
    attribution_ar: "أداء / مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "26/6 (June)",
    checkIn_ar: "٢٦/٦ (يونيو)",
    juneCash: 1102.5,
    ltv: 2205.0
  },
  {
    id: 20,
    name: "Alaa Alhayan",
    name_ar: "آلاء الحيان",
    branch: "M42",
    location: "Al Arid",
    location_ar: "العارض",
    monthlyRent: 1560,
    channel: "Friends/TikTok",
    channel_ar: "أصدقاء / تيك توك",
    attribution: "Performance/Direct",
    attribution_ar: "أداء / مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "23/6 (June)",
    checkIn_ar: "٢٣/٦ (يونيو)",
    juneCash: 468.0,
    ltv: 468.0
  },
  {
    id: 21,
    name: "Sarah AlSafar",
    name_ar: "سارة السفر",
    branch: "M15",
    location: "Al Yasmin",
    location_ar: "الياسمين",
    monthlyRent: 2500,
    channel: "Instagram",
    channel_ar: "إنستغرام",
    attribution: "Performance/Direct",
    attribution_ar: "أداء / مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "25/6 (June)",
    checkIn_ar: "٢٥/٦ (يونيو)",
    juneCash: 750.0,
    ltv: 4500.0
  },
  {
    id: 22,
    name: "Lamya Alghamdi",
    name_ar: "لمياء الغامدي",
    branch: "M38",
    location: "Al Sulaimaniyah",
    location_ar: "السليمانية",
    monthlyRent: 5000,
    channel: "Instagram",
    channel_ar: "إنستغرام",
    attribution: "Performance/Indirect",
    attribution_ar: "أداء / غير مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "25/6 (June)",
    checkIn_ar: "٢٥/٦ (يونيو)",
    juneCash: 1250.0,
    ltv: 1250.0
  },
  {
    id: 23,
    name: "Ghada Alsughayyir",
    name_ar: "غادة الصغير",
    branch: "M39",
    location: "Al Nakhil",
    location_ar: "النخيل",
    monthlyRent: 5000,
    channel: "TikTok",
    channel_ar: "تيك توك",
    attribution: "Performance/Indirect",
    attribution_ar: "أداء / غير مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "29/6 (June)",
    checkIn_ar: "٢٩/٦ (يونيو)",
    juneCash: 1500.0,
    ltv: 4500.0
  },
  {
    id: 24,
    name: "Tahreem Atta",
    name_ar: "تحريم عطا",
    branch: "M1",
    location: "King Faisal",
    location_ar: "الملك فيصل",
    monthlyRent: 3500,
    channel: "Facebook ad",
    channel_ar: "إعلان فيسبوك",
    attribution: "Performance/Direct",
    attribution_ar: "أداء / مباشر",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "27/6 (June)",
    checkIn_ar: "٢٧/٦ (يونيو)",
    juneCash: 3500.0,
    ltv: 21000.0
  },
  {
    id: 25,
    name: "Futun Alotaibi",
    name_ar: "فتون العتيبي",
    branch: "M31",
    location: "Al Salam",
    location_ar: "السلام",
    monthlyRent: 2970,
    channel: "Existing tenant",
    channel_ar: "مستأجر حالي",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "3/6 (June)",
    checkIn_ar: "٣/٦ (يونيو)",
    juneCash: 891.0,
    ltv: 10692.0
  },
  {
    id: 26,
    name: "Nima Bishr",
    name_ar: "نعمة بشر",
    branch: "M38",
    location: "Al Sulaimaniyah",
    location_ar: "السليمانية",
    monthlyRent: 4000,
    channel: "Existing tenant",
    channel_ar: "مستأجر حالي",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "1/6 (June)",
    checkIn_ar: "١/٦ (يونيو)",
    juneCash: 1000.0,
    ltv: 1000.0
  },
  {
    id: 27,
    name: "Gayatri Neti",
    name_ar: "غاياتري نيتي",
    branch: "M33",
    location: "Al Olaya",
    location_ar: "العليا",
    monthlyRent: 5600,
    channel: "(blank)",
    channel_ar: "-",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "6/6 (June)",
    checkIn_ar: "٦/٦ (يونيو)",
    juneCash: 1400.0,
    ltv: 16800.0
  },
  {
    id: 28,
    name: "Ahmed Farrag",
    name_ar: "أحمد فراج",
    branch: "M33",
    location: "Al Olaya",
    location_ar: "العليا",
    monthlyRent: 6500,
    channel: "Bayut",
    channel_ar: "بيوت",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "9/6 (June)",
    checkIn_ar: "٩/٦ (يونيو)",
    juneCash: 1625.0,
    ltv: 19500.0
  },
  {
    id: 29,
    name: "Fatma Almohsen",
    name_ar: "فاطمة المحسن",
    branch: "M42",
    location: "Al Arid",
    location_ar: "العارض",
    monthlyRent: 1700,
    channel: "Friend (WOM)",
    channel_ar: "صديق (شفهي)",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "27/6 (June)",
    checkIn_ar: "٢٧/٦ (يونيو)",
    juneCash: 510.0,
    ltv: 1020.0
  },
  {
    id: 30,
    name: "Noor Alalwan",
    name_ar: "نور العلوان",
    branch: "M42",
    location: "Al Arid",
    location_ar: "العارض",
    monthlyRent: 1700,
    channel: "Friend (WOM)",
    channel_ar: "صديق (شفهي)",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "27/6 (June)",
    checkIn_ar: "٢٧/٦ (يونيو)",
    juneCash: 510.0,
    ltv: 1020.0
  },
  {
    id: 31,
    name: "Moayad Alsayad",
    name_ar: "مؤيد الصياد",
    branch: "M51",
    location: "Al Narjis",
    location_ar: "النرجس",
    monthlyRent: 6500,
    channel: "Friend (WOM)",
    channel_ar: "صديق (شفهي)",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "17/7 (July)",
    checkIn_ar: "١٧/٧ (يوليو)",
    juneCash: 0.0,
    ltv: 650.0
  },
  {
    id: 32,
    name: "Remaa Adil",
    name_ar: "ريماء عادل",
    branch: "M56",
    location: "Al Madinah",
    location_ar: "المدينة المنورة",
    monthlyRent: 8050,
    channel: "Internet search",
    channel_ar: "بحث إنترنت",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "28/6 (June)",
    checkIn_ar: "٢٨/٦ (يونيو)",
    juneCash: 1610.0,
    ltv: 1610.0
  },
  {
    id: 33,
    name: "Khalid Alhunaiti",
    name_ar: "خالد الحنيطي",
    branch: "M13",
    location: "Al Aqiq",
    location_ar: "العقيق",
    monthlyRent: 5600,
    channel: "Friend (WOM)",
    channel_ar: "صديق (شفهي)",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "1/7 (July)",
    checkIn_ar: "١/٧ (يوليو)",
    juneCash: 0.0,
    ltv: 7840.0
  },
  {
    id: 34,
    name: "Yasmeen Samaneh",
    name_ar: "ياسمين سمانة",
    branch: "M38",
    location: "Al Sulaimaniyah",
    location_ar: "السليمانية",
    monthlyRent: 4190,
    channel: "Friends (WOM)",
    channel_ar: "أصدقاء (شفهي)",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "12/6 (June)",
    checkIn_ar: "١٢/٦ (يونيو)",
    juneCash: 1047.5,
    ltv: 1047.5
  },
  {
    id: 35,
    name: "Taimoor Ahmed",
    name_ar: "تيمور أحمد",
    branch: "M56",
    location: "Al Madinah",
    location_ar: "المدينة المنورة",
    monthlyRent: 135,
    channel: "Short stay (1 day)",
    channel_ar: "إقامة قصيرة (يوم واحد)",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "18/6 (June)",
    checkIn_ar: "١٨/٦ (يونيو)",
    juneCash: 27.0,
    ltv: 27.0
  },
  {
    id: 36,
    name: "Hawra AlZaher",
    name_ar: "حوراء الظاهر",
    branch: "M18",
    location: "Al Sulaimaniyah",
    location_ar: "السليمانية",
    monthlyRent: 3400,
    channel: "Google",
    channel_ar: "جوجل",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "20/6 (June)",
    checkIn_ar: "٢٠/٦ (يونيو)",
    juneCash: 1020.0,
    ltv: 1907.4
  },
  {
    id: 37,
    name: "Hala Almuwaishir",
    name_ar: "هالة المويشير",
    branch: "M50",
    location: "Al Narjis",
    location_ar: "النرجس",
    monthlyRent: 3200,
    channel: "Existing tenant",
    channel_ar: "مستأجر حالي",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "1/7 (July)",
    checkIn_ar: "١/٧ (يوليو)",
    juneCash: 0.0,
    ltv: 3840.0
  },
  {
    id: 38,
    name: "Khairia Mandoura",
    name_ar: "خيرية مندورة",
    branch: "M25",
    location: "Al Yarmouk",
    location_ar: "اليرموك",
    monthlyRent: 2330,
    channel: "Friend (WOM)",
    channel_ar: "صديق (شفهي)",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "24/6 (June)",
    checkIn_ar: "٢٤/٦ (يونيو)",
    juneCash: 699.0,
    ltv: 699.0
  },
  {
    id: 39,
    name: "Mashael Albalawi",
    name_ar: "مشاعل البلوي",
    branch: "M38",
    location: "Al Sulaimaniyah",
    location_ar: "السليمانية",
    monthlyRent: 4420,
    channel: "Existing tenant",
    channel_ar: "مستأجر حالي",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "19/6 (June)",
    checkIn_ar: "١٩/٦ (يونيو)",
    juneCash: 1105.0,
    ltv: 3315.0
  },
  {
    id: 40,
    name: "Layan Almutairi",
    name_ar: "ليان المطيري",
    branch: "M38",
    location: "Al Sulaimaniyah",
    location_ar: "السليمانية",
    monthlyRent: 4000,
    channel: "Friend (WOM)",
    channel_ar: "صديق (شفهي)",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "26/6 (June)",
    checkIn_ar: "٢٦/٦ (يونيو)",
    juneCash: 1000.0,
    ltv: 2000.0
  },
  {
    id: 41,
    name: "Radwa Madkour",
    name_ar: "رضوى مدكور",
    branch: "M13",
    location: "Al Aqiq",
    location_ar: "العقيق",
    monthlyRent: 5500,
    channel: "Aqar portal",
    channel_ar: "بوابة عقار",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "27/6 (June)",
    checkIn_ar: "٢٧/٦ (يونيو)",
    juneCash: 1100.0,
    ltv: 13200.0
  },
  {
    id: 42,
    name: "Hira Asif",
    name_ar: "حيرة آصف",
    branch: "M33",
    location: "Al Olaya",
    location_ar: "العليا",
    monthlyRent: 7000,
    channel: "Resident referral",
    channel_ar: "إحالة من مقيم",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "30/6 (June)",
    checkIn_ar: "٣٠/٦ (يونيو)",
    juneCash: 1750.0,
    ltv: 21000.0
  },
  {
    id: 43,
    name: "Taghreed Almutairi",
    name_ar: "تغريد المطيري",
    branch: "M38",
    location: "Al Sulaimaniyah",
    location_ar: "السليمانية",
    monthlyRent: 4950,
    channel: "Google (Olaya)",
    channel_ar: "جوجل (العليا)",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "1/7 (July)",
    checkIn_ar: "١/٧ (يوليو)",
    juneCash: 0.0,
    ltv: 1237.5
  },
  {
    id: 44,
    name: "Hind Alotaibi",
    name_ar: "هند العتيبي",
    branch: "M42",
    location: "Al Arid",
    location_ar: "العارض",
    monthlyRent: 1700,
    channel: "Former resident (disc.)",
    channel_ar: "مقيم سابق (خصم)",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "1/7 (July)",
    checkIn_ar: "١/٧ (يوليو)",
    juneCash: 0.0,
    ltv: 5508.0
  },
  {
    id: 45,
    name: "Sadeem Alotaibi",
    name_ar: "سديم العتيبي",
    branch: "M42",
    location: "Al Arid",
    location_ar: "العارض",
    monthlyRent: 1700,
    channel: "Former resident (disc.)",
    channel_ar: "مقيم سابق (خصم)",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "24/6 (June)",
    checkIn_ar: "٢٤/٦ (يونيو)",
    juneCash: 153.0,
    ltv: 5508.0
  },
  {
    id: 46,
    name: "Fatma Albatbah",
    name_ar: "فاطمة البطاح",
    branch: "M38",
    location: "Al Sulaimaniyah",
    location_ar: "السليمانية",
    monthlyRent: 4600,
    channel: "Previous tenant",
    channel_ar: "مستأجر سابق",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "4/7 (July)",
    checkIn_ar: "٤/٧ (يوليو)",
    juneCash: 0.0,
    ltv: 1150.0
  },
  {
    id: 47,
    name: "Nasser Almulhim",
    name_ar: "ناصر الملحم",
    branch: "M43",
    location: "Al Ta'awun",
    location_ar: "التعاون",
    monthlyRent: 10752,
    channel: "Friends (WOM)",
    channel_ar: "أصدقاء (شفهي)",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Cancelled",
    status_ar: "ملغى",
    checkIn: "4/6 (June)",
    checkIn_ar: "٤/٦ (يونيو)",
    juneCash: 0.0,
    ltv: 0.0
  },
  {
    id: 48,
    name: "Mohammed Abdelmonem",
    name_ar: "محمد عبد المنعم",
    branch: "M33",
    location: "Al Olaya",
    location_ar: "العليا",
    monthlyRent: 5400,
    channel: "Friend (WOM)",
    channel_ar: "صديق (شفهي)",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Cancelled",
    status_ar: "ملغى",
    checkIn: "17/6 (June)",
    checkIn_ar: "١٧/٦ (يونيو)",
    juneCash: 0.0,
    ltv: 0.0
  },
  {
    id: 49,
    name: "Maimouna Hajouri",
    name_ar: "ميمونة هجوري",
    branch: "M38",
    location: "Al Sulaimaniyah",
    location_ar: "السليمانية",
    monthlyRent: 5000,
    channel: "TikTok",
    channel_ar: "تيك توك",
    attribution: "Performance",
    attribution_ar: "أداء",
    status: "Cancelled",
    status_ar: "ملغى",
    checkIn: "23/6 (June)",
    checkIn_ar: "٢٣/٦ (يونيو)",
    juneCash: 0.0,
    ltv: 0.0
  },
  {
    id: 50,
    name: "Nawar Batweel",
    name_ar: "نوار باتويل",
    branch: "M38",
    location: "Al Sulaimaniyah",
    location_ar: "السليمانية",
    monthlyRent: 4550,
    channel: "Friend (WOM)",
    channel_ar: "صديق (شفهي)",
    attribution: "Other",
    attribution_ar: "مصادر أخرى",
    status: "Cancelled",
    status_ar: "ملغى",
    checkIn: "27/6 (June)",
    checkIn_ar: "٢٧/٦ (يونيو)",
    juneCash: 0.0,
    ltv: 0.0
  },
  {
    id: 51,
    name: "Mai Alghunaimi",
    name_ar: "مي الغنيمي",
    branch: "M32",
    location: "Al Qayrawan",
    location_ar: "القيروان",
    monthlyRent: 2600,
    channel: "Instagram",
    channel_ar: "إنستغرام",
    attribution: "Performance",
    attribution_ar: "أداء",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "14/6 (June)",
    checkIn_ar: "١٤/٦ (يونيو)",
    juneCash: 650.0,
    ltv: 3900.0
  },
  {
    id: 52,
    name: "Nouf Ahmed (Bin Ghadeer)",
    name_ar: "نوف أحمد (بن غدير)",
    branch: "M38",
    location: "Al Sulaimaniyah",
    location_ar: "السليمانية",
    monthlyRent: 4350,
    channel: "Instagram",
    channel_ar: "إنستغرام",
    attribution: "Performance",
    attribution_ar: "أداء",
    status: "Approved",
    status_ar: "مقبول",
    checkIn: "14/6 (June)",
    checkIn_ar: "١٤/٦ (يونيو)",
    juneCash: 1087.5,
    ltv: 6525.0
  }
];

export const SYNC_DATA = {
  reportingPeriod: "1–28 June 2026",
  reportingPeriodAr: "١-٢٨ يونيو ٢٠٢٦",
  
  // Hero KPIs
  heroKPIs: {
    juneCashCollected: 39879.5,
    performanceCash: 24431.5,
    performanceCashPct: 61.3,
    totalLtvGenerated: 222333,
    approvedCount: 48,
    cancelledCount: 4,
    renewalCount: 0
  },

  // Section 2: June Cash Performance vs Other
  sourceBreakdown: [
    {
      source: "Performance marketing",
      source_ar: "التسويق بالأداء",
      juneCash: 24431.5,
      pctOfCash: 61.3,
      ltv: 101762,
      color: "#4A2C5A"
    },
    {
      source: "Other sources",
      source_ar: "مصادر أخرى",
      juneCash: 15448,
      pctOfCash: 38.7,
      ltv: 120571,
      color: "#86868b"
    }
  ],

  // Section 3: Direct vs Indirect
  directIndirectBreakdown: [
    {
      type: "Direct (branch has live campaign)",
      type_ar: "مباشر (الحملة نشطة للفرع)",
      juneCash: 18341.5,
      ltv: 87972,
      pctOfPerfCash: 75.1,
      color: "#4A2C5A"
    },
    {
      type: "Indirect / spillover",
      type_ar: "غير مباشر / تأثير غير مباشر",
      juneCash: 6090,
      ltv: 13790,
      pctOfPerfCash: 24.9,
      color: "#A855F7"
    }
  ],

  // Section 4: July Start Bookings
  julyStartBookings: [
    { name: "Shahad Alotaibi", name_ar: "شهد العتيبي", branch: "M31", ltv: 11880 },
    { name: "Khalid Alhunaiti", name_ar: "خالد الحنيطي", branch: "M13", ltv: 7840 },
    { name: "Hala Almuwaishir", name_ar: "هالة المويشير", branch: "M50", ltv: 3840 },
    { name: "Taghreed Almutairi", name_ar: "تغريد المطيري", branch: "M38", ltv: 1238 },
    { name: "Hind Alotaibi", name_ar: "هند العتيبي", branch: "M42", ltv: 5508 },
    { name: "Moayad Alsayad", name_ar: "مؤيد الصياد", branch: "M51", ltv: 650 },
    { name: "Fatma Albatbah", name_ar: "فاطمة البطاح", branch: "M38", ltv: 1150 }
  ],
  julyStartLtvTotal: 32106
};
