export interface CustomerPayment {
  id: number;
  inputName: string;
  matchedName: string;
  matchedNameAr: string;
  status: 'Confirmed' | 'Pending Approval' | 'Due July' | 'Facing Issue' | 'Pending Payment';
  status_ar: string;
  reason: string;
  reason_ar: string;
  rent: number;
  juneCash: number;
  branch: string;
}

export const CUSTOMER_PAYMENTS: CustomerPayment[] = [
  {
    "id": 1,
    "inputName": "امل العنزي",
    "matchedName": "Amal Alenazi",
    "matchedNameAr": "أمل العنزي",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 5444,
    "juneCash": 1361,
    "branch": "M38"
  },
  {
    "id": 2,
    "inputName": "ضي الجميل",
    "matchedName": "Day Aljameel",
    "matchedNameAr": "ضي الجميل",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 4500,
    "juneCash": 1350,
    "branch": "M23"
  },
  {
    "id": 3,
    "inputName": "اميمه عابدين",
    "matchedName": "Omaima Abdeen",
    "matchedNameAr": "أميمة عابدين",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 2500,
    "juneCash": 500,
    "branch": "M20"
  },
  {
    "id": 4,
    "inputName": "فئ العيافي",
    "matchedName": "Fai Alayafi",
    "matchedNameAr": "فيء العيافي",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 4500,
    "juneCash": 1125,
    "branch": "M32"
  },
  {
    "id": 5,
    "inputName": "هبه الهوساوي",
    "matchedName": "Heba Hosawi",
    "matchedNameAr": "هبة هوساوي",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 2400,
    "juneCash": 480,
    "branch": "M20"
  },
  {
    "id": 6,
    "inputName": "شعاع آل مغيره",
    "matchedName": "Shuaa Almoghira",
    "matchedNameAr": "شعاع المغيرة",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 4790,
    "juneCash": 1197.5,
    "branch": "M38"
  },
  {
    "id": 7,
    "inputName": "عذاري القلهاتي",
    "matchedName": "Athari Alqalhati",
    "matchedNameAr": "أثاري القلحاطي",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 2600,
    "juneCash": 780,
    "branch": "M37"
  },
  {
    "id": 8,
    "inputName": "زهراء البصري",
    "matchedName": "Zahraa Albasri",
    "matchedNameAr": "زهراء البصري",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 2900,
    "juneCash": 580,
    "branch": "M7"
  },
  {
    "id": 9,
    "inputName": "فيصل الحصيني",
    "matchedName": "Faisal Alhussaini",
    "matchedNameAr": "فيصل الحسيني",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 4800,
    "juneCash": 960,
    "branch": "M13"
  },
  {
    "id": 10,
    "inputName": "شهد العتيبي",
    "matchedName": "Shahad Alotaibi",
    "matchedNameAr": "شهد العتيبي",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 3300,
    "juneCash": 0,
    "branch": "M31"
  },
  {
    "id": 11,
    "inputName": "فاطمه وليد",
    "matchedName": "Fatma Alwasmi",
    "matchedNameAr": "فاطمة الوسمي",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 2900,
    "juneCash": 580,
    "branch": "M6"
  },
  {
    "id": 12,
    "inputName": "دانه الشطب",
    "matchedName": "Dana Alshatab",
    "matchedNameAr": "دانة الشطب",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 4345,
    "juneCash": 1086.25,
    "branch": "M38"
  },
  {
    "id": 13,
    "inputName": "شهد الشهري",
    "matchedName": "Shahad Alshehri",
    "matchedNameAr": "شهد الشهري",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 2800,
    "juneCash": 280,
    "branch": "M51"
  },
  {
    "id": 14,
    "inputName": "سلافه البيشي",
    "matchedName": "Sulaf Albeshi",
    "matchedNameAr": "سلاف البيشي",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 2330,
    "juneCash": 699,
    "branch": "M25"
  },
  {
    "id": 15,
    "inputName": "فاطمه الدوسري",
    "matchedName": "Fatma Aldosari",
    "matchedNameAr": "فاطمة الدوسري",
    "status": "Pending Approval",
    "status_ar": "بانتظار موافقة المستأجر",
    "reason": "Awaiting tenant approval",
    "reason_ar": "بانتظار موافقة المستأجر",
    "rent": 3300,
    "juneCash": 990,
    "branch": "M39"
  },
  {
    "id": 16,
    "inputName": "مجد العتيبي",
    "matchedName": "Majd Alotaibi",
    "matchedNameAr": "مجد العتيبي",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 2700,
    "juneCash": 540,
    "branch": "M20"
  },
  {
    "id": 17,
    "inputName": "حور التركي",
    "matchedName": "Hoor Alturki",
    "matchedNameAr": "حور التركي",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 4420,
    "juneCash": 1105,
    "branch": "M38"
  },
  {
    "id": 18,
    "inputName": "ساره المطيري",
    "matchedName": "Sarah Almutairi",
    "matchedNameAr": "سارة المطيري",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 1700,
    "juneCash": 510,
    "branch": "M42"
  },
  {
    "id": 19,
    "inputName": "منيره التركي",
    "matchedName": "Munira Alturki",
    "matchedNameAr": "منيرة التركي",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 4410,
    "juneCash": 1102.5,
    "branch": "M38"
  },
  {
    "id": 20,
    "inputName": "آلاء الحيان",
    "matchedName": "Alaa Alhayan",
    "matchedNameAr": "آلاء الحيان",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 1560,
    "juneCash": 468,
    "branch": "M42"
  },
  {
    "id": 21,
    "inputName": "ساره آل سفر",
    "matchedName": "Sarah AlSafar",
    "matchedNameAr": "سارة السفر",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 2500,
    "juneCash": 750,
    "branch": "M15"
  },
  {
    "id": 22,
    "inputName": "لمياء الغامدي",
    "matchedName": "Lamya Alghamdi",
    "matchedNameAr": "لمياء الغامدي",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 5000,
    "juneCash": 1250,
    "branch": "M38"
  },
  {
    "id": 23,
    "inputName": "غاده الصغير",
    "matchedName": "Ghada Alsughayyir",
    "matchedNameAr": "غادة الصغير",
    "status": "Pending Payment",
    "status_ar": "بانتظار السداد",
    "reason": "Awaiting payment transfer",
    "reason_ar": "بانتظار السداد",
    "rent": 5000,
    "juneCash": 1500,
    "branch": "M39"
  },
  {
    "id": 24,
    "inputName": "Tahreem atta",
    "matchedName": "Tahreem Atta",
    "matchedNameAr": "تحريم عطا",
    "status": "Pending Approval",
    "status_ar": "بانتظار موافقة المستأجر",
    "reason": "Awaiting tenant approval",
    "reason_ar": "بانتظار موافقة المستأجر",
    "rent": 3500,
    "juneCash": 3500,
    "branch": "M1"
  },
  {
    "id": 25,
    "inputName": "فتون العتيبي",
    "matchedName": "Futun Alotaibi",
    "matchedNameAr": "فتون العتيبي",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 2970,
    "juneCash": 891,
    "branch": "M31"
  },
  {
    "id": 26,
    "inputName": "نعمه يحي",
    "matchedName": "Nima Bishr",
    "matchedNameAr": "نعمة بشر",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 4000,
    "juneCash": 1000,
    "branch": "M38"
  },
  {
    "id": 27,
    "inputName": "Gayatri",
    "matchedName": "Gayatri Neti",
    "matchedNameAr": "غاياتري نيتي",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 5600,
    "juneCash": 1400,
    "branch": "M33"
  },
  {
    "id": 28,
    "inputName": "احمد فراج",
    "matchedName": "Ahmed Farrag",
    "matchedNameAr": "أحمد فراج",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 6500,
    "juneCash": 1625,
    "branch": "M33"
  },
  {
    "id": 29,
    "inputName": "فاطمه المحسن",
    "matchedName": "Fatma Almohsen",
    "matchedNameAr": "فاطمة المحسن",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 1700,
    "juneCash": 510,
    "branch": "M42"
  },
  {
    "id": 30,
    "inputName": "نور العلوان",
    "matchedName": "Noor Alalwan",
    "matchedNameAr": "نور العلوان",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 1700,
    "juneCash": 510,
    "branch": "M42"
  },
  {
    "id": 31,
    "inputName": "مؤيد السيد",
    "matchedName": "Moayad Alsayad",
    "matchedNameAr": "مؤيد الصياد",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 6500,
    "juneCash": 0,
    "branch": "M51"
  },
  {
    "id": 32,
    "inputName": "Reema adil",
    "matchedName": "Remaa Adil",
    "matchedNameAr": "ريماء عادل",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 8050,
    "juneCash": 1610,
    "branch": "M56"
  },
  {
    "id": 33,
    "inputName": "خالد الحنيطي",
    "matchedName": "Khalid Alhunaiti",
    "matchedNameAr": "خالد الحنيطي",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 5600,
    "juneCash": 0,
    "branch": "M13"
  },
  {
    "id": 34,
    "inputName": "ياسمين سماعنه",
    "matchedName": "Yasmeen Samaneh",
    "matchedNameAr": "ياسمين سمانة",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 4190,
    "juneCash": 1047.5,
    "branch": "M38"
  },
  {
    "id": 35,
    "inputName": "Taimoor Ahmad",
    "matchedName": "Taimoor Ahmed",
    "matchedNameAr": "تيمور أحمد",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 135,
    "juneCash": 27,
    "branch": "M56"
  },
  {
    "id": 36,
    "inputName": "حوراء ال زاهر",
    "matchedName": "Hawra AlZaher",
    "matchedNameAr": "حوراء الظاهر",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 3400,
    "juneCash": 1020,
    "branch": "M18"
  },
  {
    "id": 37,
    "inputName": "هلا المويشير",
    "matchedName": "Hala Almuwaishir",
    "matchedNameAr": "هالة المويشير",
    "status": "Due July",
    "status_ar": "استحقاق القسط 1 يوليو",
    "reason": "Installment due on July 1st",
    "reason_ar": "استحقاق القسط في 1 يوليو",
    "rent": 3200,
    "juneCash": 0,
    "branch": "M50"
  },
  {
    "id": 38,
    "inputName": "خيريه اسماعيل",
    "matchedName": "Khairia Mandoura",
    "matchedNameAr": "خيرية مندورة",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 2330,
    "juneCash": 699,
    "branch": "M25"
  },
  {
    "id": 39,
    "inputName": "مشاعل البلوي",
    "matchedName": "Mashael Albalawi",
    "matchedNameAr": "مشاعل البلوي",
    "status": "Due July",
    "status_ar": "استحقاق القسط 1 يوليو",
    "reason": "Installment due on July 1st",
    "reason_ar": "استحقاق القسط في 1 يوليو",
    "rent": 4420,
    "juneCash": 1105,
    "branch": "M38"
  },
  {
    "id": 40,
    "inputName": "ليان المطيري",
    "matchedName": "Layan Almutairi",
    "matchedNameAr": "ليان المطيري",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 4000,
    "juneCash": 1000,
    "branch": "M38"
  },
  {
    "id": 41,
    "inputName": "رضوى مدكور",
    "matchedName": "Radwa Madkour",
    "matchedNameAr": "رضوى مدكور",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 5500,
    "juneCash": 1100,
    "branch": "M13"
  },
  {
    "id": 42,
    "inputName": "Hira asif",
    "matchedName": "Hira Asif",
    "matchedNameAr": "حيرة آصف",
    "status": "Facing Issue",
    "status_ar": "تواجه مشكلة بتكلمنا اليوم بعد دوامها",
    "reason": "Technical issue, will contact us after work",
    "reason_ar": "تواجه مشكلة بتكلمنا اليوم بعد دوامها",
    "rent": 7000,
    "juneCash": 1750,
    "branch": "M33"
  },
  {
    "id": 43,
    "inputName": "تغريد خلف",
    "matchedName": "Taghreed Almutairi",
    "matchedNameAr": "تغريد المطيري",
    "status": "Pending Approval",
    "status_ar": "بانتظار موافقة المستأجر",
    "reason": "Awaiting tenant approval",
    "reason_ar": "بانتظار موافقة المستأجر",
    "rent": 4950,
    "juneCash": 0,
    "branch": "M38"
  },
  {
    "id": 44,
    "inputName": "هند العتيبي",
    "matchedName": "Hind Alotaibi",
    "matchedNameAr": "هند العتيبي",
    "status": "Pending Payment",
    "status_ar": "بانتظار السداد",
    "reason": "Awaiting payment transfer",
    "reason_ar": "بانتظار السداد",
    "rent": 1700,
    "juneCash": 0,
    "branch": "M42"
  },
  {
    "id": 45,
    "inputName": "سديم العتيبي",
    "matchedName": "Sadeem Alotaibi",
    "matchedNameAr": "سديم العتيبي",
    "status": "Pending Payment",
    "status_ar": "بانتظار السداد",
    "reason": "Awaiting payment transfer",
    "reason_ar": "بانتظار السداد",
    "rent": 1700,
    "juneCash": 153,
    "branch": "M42"
  },
  {
    "id": 46,
    "inputName": "فاطمة سامي",
    "matchedName": "Fatma Albatbah",
    "matchedNameAr": "فاطمة البطاح",
    "status": "Pending Payment",
    "status_ar": "بانتظار السداد",
    "reason": "Awaiting payment transfer",
    "reason_ar": "بانتظار السداد",
    "rent": 4600,
    "juneCash": 0,
    "branch": "M38"
  },
  {
    "id": 47,
    "inputName": "ناصر الملحم",
    "matchedName": "Nasser Almulhim",
    "matchedNameAr": "ناصر الملحم",
    "status": "Facing Issue",
    "status_ar": "ملغى / مشكلة",
    "reason": "Booking is Cancelled",
    "reason_ar": "الحجز ملغى",
    "rent": 10752,
    "juneCash": 0,
    "branch": "M43"
  },
  {
    "id": 48,
    "inputName": "محمد عبد المنعم",
    "matchedName": "Mohammed Abdelmonem",
    "matchedNameAr": "محمد عبد المنعم",
    "status": "Facing Issue",
    "status_ar": "ملغى / مشكلة",
    "reason": "Booking is Cancelled",
    "reason_ar": "الحجز ملغى",
    "rent": 5400,
    "juneCash": 0,
    "branch": "M33"
  },
  {
    "id": 49,
    "inputName": "ميمونه حجوري",
    "matchedName": "Maimouna Hajouri",
    "matchedNameAr": "ميمونة هجوري",
    "status": "Facing Issue",
    "status_ar": "ملغى / مشكلة",
    "reason": "Booking is Cancelled",
    "reason_ar": "الحجز ملغى",
    "rent": 5000,
    "juneCash": 0,
    "branch": "M38"
  },
  {
    "id": 50,
    "inputName": "نوار باتويل",
    "matchedName": "Nawar Batweel",
    "matchedNameAr": "نوار باتويل",
    "status": "Facing Issue",
    "status_ar": "ملغى / مشكلة",
    "reason": "Booking is Cancelled",
    "reason_ar": "الحجز ملغى",
    "rent": 4550,
    "juneCash": 0,
    "branch": "M38"
  },
  {
    "id": 51,
    "inputName": "مي الغنيمي",
    "matchedName": "Mai Alghunaimi",
    "matchedNameAr": "مي الغنيمي",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 2600,
    "juneCash": 650,
    "branch": "M32"
  },
  {
    "id": 52,
    "inputName": "نوف احمد",
    "matchedName": "Nouf Ahmed (Bin Ghadeer)",
    "matchedNameAr": "نوف أحمد (بن غدير)",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 4350,
    "juneCash": 1087.5,
    "branch": "M38"
  },
  {
    "id": 53,
    "inputName": "لانا محمد",
    "matchedName": "Lanaa Muhammad",
    "matchedNameAr": "لانا محمد",
    "status": "Confirmed",
    "status_ar": "مؤكد",
    "reason": "",
    "reason_ar": "",
    "rent": 4500,
    "juneCash": 1125,
    "branch": "M38"
  }
];
